name: Validate

on:
  workflow_dispatch:
  push:

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.44 # https://github.com/golangci/golangci-lint/releases
  gomod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17 # https://golang.org/dl/
      - name: Go Mod Tidy
        run: test -z $(go mod tidy)
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17 # https://golang.org/dl/
      - name: Test
        run: go test -cover -coverprofile=c.out -covermode=atomic -race -v ./...
